fix(driver): fix build on RHEL 9.3 kernels (#197)
On recent RHEL9 kernels (namely starting with 5.14.0-327.el9)
the kmod driver will fail to build with the following error:

```
./main.c: In function 'scap_init':
./main.c:2896:30: error: assignment to 'char * (*)(const struct device *, umode_t *)' {aka 'char * (*)(const struct device *, short unsigned int *)'} from incompatible pointer type 'char * (*)(struct device *, umode_t *)' {aka 'char * (*)(struct device *, short unsigned int *)'} [-Werror=incompatible-pointer-types]
         g_ppm_class->devnode = ppm_devnode;
                              ^
cc1: all warnings being treated as errors
```

Notice how Red Hat backported that change from kernel 6.2
into what looks like 5.14 for RHEL9.3.

See for instance:
```
$ head -2 */usr/src/kernels/5.14.0-283.el9.x86_64/Makefile.rhelver
RHEL_MAJOR = 9
RHEL_MINOR = 2
```
vs
```
$ head -2 */usr/src/kernels/5.14.0-327.el9.x86_64/Makefile.rhelver
RHEL_MAJOR = 9
RHEL_MINOR = 3
```

Signed-off-by: Gerlando Falauto <gerlando.falauto@sysdig.com>
Co-authored-by: Angelo Puglisi <angelo.puglisi@sysdig.com>